# Workflow Engine Server Configuration
# Supports environment variable injection using ${VAR_NAME:default_value} syntax

# Project settings
project:
  # Project root directory (auto-detected if not specified)
  root: "${WORKFLOW_PROJECT_ROOT:}"
  # Source directory relative to project root
  source_dir: "${WORKFLOW_SOURCE_DIR:src_new}"

# Server settings
server:
  host: "${WORKFLOW_HOST:0.0.0.0}"
  port: ${WORKFLOW_PORT:8889}
  title: "${WORKFLOW_TITLE:Ren Engine}"
  description: "${WORKFLOW_DESCRIPTION:轻量级本地工作流引擎 API}"
  version: "${WORKFLOW_VERSION:1.0.0}"

# Application settings
apps:
  # Applications directory path (relative to project root)
  directory: "${WORKFLOW_APPS_DIR:apps}"
  # Auto-reload apps on changes
  auto_reload: ${WORKFLOW_AUTO_RELOAD:true}

# Database settings
database:
  # Database file path - uses platform-independent user data directory
  # Windows: %APPDATA%/workflow_engine/workflow.db
  # macOS/Linux: ~/.local/share/workflow_engine/workflow.db
  path: "${WORKFLOW_DB_PATH:}"

# Logging settings
logging:
  level: "${WORKFLOW_LOG_LEVEL:INFO}"
  # Log directory - uses platform-independent user data directory
  # Windows: %APPDATA%/workflow_engine/logs
  # macOS/Linux: ~/.local/share/workflow_engine/logs
  directory: "${WORKFLOW_LOG_DIR:}"
  # Enable console output for real-time log viewing
  console_output: ${WORKFLOW_CONSOLE_OUTPUT:true}
  # Console log format (simple, detailed, json)
  console_format: "${WORKFLOW_CONSOLE_FORMAT:detailed}"

# Templates settings
templates:
  # Templates directory (relative to workflow_engine package)
  directory: "${WORKFLOW_TEMPLATES_DIR:templates}"

# Development settings
development:
  # Enable debug mode
  debug: ${WORKFLOW_DEBUG:false}
  # Enable auto-reload
  reload: ${WORKFLOW_RELOAD:true}

# Cross-platform data directories
# These will be resolved programmatically based on the platform
data_dirs:
  # Base data directory for the application
  # Windows: %APPDATA%/workflow_engine
  # macOS: ~/Library/Application Support/workflow_engine
  # Linux: ~/.local/share/workflow_engine
  base: "${WORKFLOW_DATA_DIR:}"

  # Cache directory
  # Windows: %LOCALAPPDATA%/workflow_engine/cache
  # macOS: ~/Library/Caches/workflow_engine
  # Linux: ~/.cache/workflow_engine
  cache: "${WORKFLOW_CACHE_DIR:}"

  # Temporary directory
  # Uses system temp directory with workflow_engine subdirectory
  temp: "${WORKFLOW_TEMP_DIR:}"

  # Upload directory for file uploads
  # Default: base_dir/uploads
  upload: "${WORKFLOW_UPLOAD_DIR:}"

  # Logs directory for workflow execution logs
  # Default: base_dir/logs
  logs: "${WORKFLOW_LOG_DIR:}"