server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ozon-product-selector
  
  ai:
    alibaba:
      dashscope:
        chat:
          api-key: ${DASHSCOPE_API_KEY:your-dashscope-api-key}
          model: qwen-plus
          options:
            temperature: 0.3
            max-tokens: 2000
  
  datasource:
    url: jdbc:h2:mem:ozondb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  cache:
    type: simple
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

# OZON API Configuration
ozon:
  api:
    base-url: https://api-seller.ozon.ru
    client-id: ${OZON_CLIENT_ID:your-client-id}
    api-key: ${OZON_API_KEY:your-api-key}
    rate-limit:
      requests-per-minute: 100
      burst-capacity: 10

# Product Analysis Configuration  
product:
  analysis:
    batch-size: 50
    cache-duration: PT1H
    ai:
      prompt-template: |
        Analyze the following OZON product data and provide insights for product selection:
        
        Product: {productName}
        Category: {category}
        Price: {price}
        Sales Volume: {salesVolume}
        Rating: {rating}
        Reviews Count: {reviewsCount}
        
        Please analyze:
        1. Market potential and competition level
        2. Profit margin estimation
        3. Seasonality trends
        4. Risk assessment
        5. Recommendation score (1-10)
        
        Provide a structured JSON response with your analysis.

  # Product Pool Configuration
  pool:
    batch-size: 100
    categories: 
      - 15621  # 电子产品
      - 17029  # 家居用品
      - 15621  # 运动户外
      - 15621  # 服装鞋帽
      - 15621  # 母婴用品
      - 15621  # 美容护肤
      - 15621  # 汽车用品
      - 15621  # 图书音像
    min-rating: 3.5
    min-reviews: 10
    refresh-interval: PT24H
    data-sources:
      trending:
        enabled: true
        batch-size: 100
        min-rating: 4.0
      category:
        enabled: true
        batch-size: 50
        per-category: true
      keyword:
        enabled: true
        batch-size: 30
        keywords:
          - "智能手机"
          - "笔记本电脑"
          - "健身器材"
          - "家居用品"
          - "母婴用品"
          - "美容护肤"
          - "运动装备"
          - "数码配件"
          - "厨房用具"
          - "办公用品"
      competitor:
        enabled: true
        similarity-threshold: 0.8
        price-range-factor: 0.5  # 50%-150% price range

# Scheduling Configuration
scheduling:
  enabled: true
  market-data-refresh: "0 0 */6 * * *"  # Every 6 hours
  trend-analysis: "0 30 2 * * *"        # Daily at 2:30 AM

# Logging Configuration
logging:
  level:
    com.ozon.tools: DEBUG
    org.springframework.ai: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ozon-product-selector.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
