spring:
  ai:
    alibaba:
      dashscope:
        chat:
          api-key: "test-api-key"
          model: qwen-plus
          options:
            temperature: 0.3
            max-tokens: 2000

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

ozon:
  api:
    base-url: https://api-seller.ozon.ru
    client-id: "test-client-id"
    api-key: "test-api-key"
    rate-limit:
      requests-per-minute: 100

logging:
  level:
    com.ozon.tools: DEBUG
    org.springframework.ai: WARN
