# Spec-Kit Workflow Configuration
name: AI Product Selector Spec-Kit Workflow
version: "1.0.0"

# Core Workflow Steps
workflow:
  constitution:
    description: "Establish project principles and governance"
    command: "speckit.constitution"
    output: ".specify/memory/constitution.md"
    required: true
    
  specify:
    description: "Create feature specification from requirements"
    command: "speckit.specify"
    template: ".specify/templates/spec-template.md"
    output_pattern: "specs/{feature-number}-{feature-name}/spec.md"
    dependencies: ["constitution"]
    
  plan:
    description: "Create implementation plan from specification"
    command: "speckit.plan"
    template: ".specify/templates/plan-template.md"
    output_pattern: "specs/{feature-number}-{feature-name}/plan.md"
    dependencies: ["specify"]
    
  tasks:
    description: "Break down plan into actionable tasks"
    command: "speckit.tasks"
    template: ".specify/templates/tasks-template.md"
    output_pattern: "specs/{feature-number}-{feature-name}/tasks.md"
    dependencies: ["plan"]
    
  implement:
    description: "Execute implementation from tasks"
    command: "speckit.implement"
    dependencies: ["tasks"]

# Optional Enhancement Commands
enhancements:
  clarify:
    description: "Ask structured questions to reduce ambiguity"
    command: "speckit.clarify"
    
  analyze:
    description: "Cross-artifact consistency analysis"
    command: "speckit.analyze"
    
  checklist:
    description: "Generate quality validation checklists"
    command: "speckit.checklist"
    template: ".specify/templates/checklist-template.md"

# Team Collaboration Settings
collaboration:
  feature_isolation: true
  spec_review_required: true
  implementation_follows_spec: true
  conflict_resolution: "specification-first"
  
# Quality Gates
quality:
  spec_completeness_check: true
  plan_feasibility_review: true
  task_clarity_validation: true
  implementation_spec_alignment: true